apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /var/nfsshare
    server: 172.16.86.162
