kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc-dynamic-test
  annotations:
    volume.beta.kubernetes.io/storage-class: cinder-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
