apiVersion: v1
kind: Pod
metadata:
  name: external
  namespace: demo
  labels:
    role: External
spec:
  containers:
      - name: redismaster
        image: redis  # or just image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: demo
  labels:
    role: WebFrontend
spec:
  containers:
      - name: redismaster
        image: redis  # or just image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: demo
  labels:
    role: BusinessBackend
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 6379
